# Generated by Django 3.0.8 on 2020-07-26 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main-page', '0003_auto_20200725_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocacy',
            name='entry_date',
            field=models.DateField(default=datetime.date.today, help_text='mm/dd/yyyy'),
        ),
        migrations.AddField(
            model_name='clinical',
            name='entry_date',
            field=models.DateField(default=datetime.date.today, help_text='mm/dd/yyyy'),
        ),
        migrations.AddField(
            model_name='map',
            name='entry_date',
            field=models.DateField(default=datetime.date.today, help_text='mm/dd/yyyy'),
        ),
        migrations.AddField(
            model_name='ov',
            name='entry_date',
            field=models.DateField(default=datetime.date.today, help_text='mm/dd/yyyy'),
        ),
        migrations.AddField(
            model_name='safe_clinic',
            name='entry_date',
            field=models.DateField(default=datetime.date.today, help_text='mm/dd/yyyy'),
        ),
    ]
