# Generated by Django 3.0.8 on 2020-08-01 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main-page', '0007_auto_20200726_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prevention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('type_org', models.CharField(blank=True, choices=[('church', 'church'), ('college/university', 'college/university'), ('high school', 'high school'), ('elementary school', 'elementary school'), ('middle school', 'middle school'), ('non-profit', 'non-profit'), ('corporation', 'corporation'), ('bar/restaurant', 'bar/restaurant'), ('other', 'other')], max_length=30, verbose_name='Total Individuals')),
                ('num_attendees', models.PositiveIntegerField(verbose_name='Number of Attendees')),
                ('duration', models.PositiveIntegerField(verbose_name='Training Duration')),
                ('topic', models.CharField(blank=True, choices=[('stewards of children', 'stewards of children'), ('safe bar', 'safe bar'), ('other', 'other')], max_length=30, verbose_name='Topic of Training')),
                ('topic_other', models.TextField(verbose_name='Other Topic')),
            ],
            options={
                'verbose_name': 'Prevention Team Entry',
                'verbose_name_plural': 'Prevention Team Entries',
            },
        ),
    ]
