# Generated by Django 3.0.8 on 2020-08-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main-page', '0008_prevention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevention',
            name='type_org',
            field=models.CharField(blank=True, choices=[('church', 'church'), ('college/university', 'college/university'), ('high school', 'high school'), ('elementary school', 'elementary school'), ('middle school', 'middle school'), ('non-profit', 'non-profit'), ('corporation', 'corporation'), ('bar/restaurant', 'bar/restaurant'), ('other', 'other')], max_length=30, verbose_name='Type of Organization'),
        ),
    ]
