# Generated by Django 3.0.8 on 2020-08-02 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main-page', '0009_auto_20200731_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('new_donors', models.PositiveIntegerField(verbose_name='New Donors')),
                ('new_foundations', models.PositiveIntegerField(verbose_name='New Foundations/Grants')),
                ('over_1000', models.PositiveIntegerField(verbose_name='Gifts over $1000')),
                ('recurring_donors', models.PositiveIntegerField(verbose_name='Recurring Donors')),
                ('recurring_gift_avg', models.PositiveIntegerField(verbose_name='Recurring Gift Average')),
                ('total_raised', models.PositiveIntegerField(verbose_name='Total Amount Raised')),
                ('percent_goal_met', models.PositiveIntegerField(verbose_name='Percentage of Monthly Goal Met')),
            ],
            options={
                'verbose_name': 'Development Team Entry',
                'verbose_name_plural': 'Development Team Entries',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('occupation', models.CharField(blank=True, choices=[('advocacy organization staff', 'advocacy org staff'), ('attorneys/law students (not prosecutor)', 'attorneys/law students'), ('batterer intervention program staff', 'batterer intervention program staff'), ('corrections personnel', 'corrections personnel'), ('court personnel', 'court personnel'), ('disability organization staff', 'disability org staff'), ('educators', 'educators'), ('elder organization staff', 'elder org staff'), ('faith-based organization staff', 'faith-based org staff'), ('government agency staff', 'gov agency staff'), ('health professionals', 'health professionals'), ('immigrant organization staff', 'immigrant org staff'), ('law enforcement officers', 'law enforcement officers'), ('legal services staff (not attorney)', 'legal services staff'), ('mental health professionals', 'mental health professionals'), ('prosecutors', 'prosecutors'), ('sex offender treatment providers', 'sex offender treatment providers'), ('sexual assault nurse/forensic examiners', 'sexual assault nurse/forensic examiners'), ('social service organization staff (non government)', 'social service org staff'), ('substance abuse organization staff', 'substance abuse org staff'), ('supervised visitation and exchange center staff', 'supervised vistation and exchange center'), ('translators/interpreters', 'translators/interpreters'), ('tribal government/tribal government agency staff', 'tribal government/tribal government agency staff'), ('victim advocates (non-government)', 'victim advocates'), ('victim assistants (government)', 'victim assistants'), ('volunteers', 'volunteers'), ('other', 'other')], max_length=50, verbose_name='Occupation of Trainees')),
                ('num_attendees', models.PositiveIntegerField(verbose_name='Number of Attendees')),
                ('duration', models.PositiveIntegerField(verbose_name='Training Duration')),
                ('training_type', models.CharField(blank=True, choices=[('training', 'training'), ('wellness retreat', 'wellness retreat'), ('peer support collaborative', 'peer support collaborative'), ('other', 'other')], max_length=50, verbose_name='Type of Training')),
                ('training_type_other', models.TextField(verbose_name='Type of Training - Other Text')),
            ],
            options={
                'verbose_name': 'Training Team Entry',
                'verbose_name_plural': 'Training Team Entries',
            },
        ),
    ]
