# Generated by Django 3.0.8 on 2020-08-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main-page', '0011_auto_20200801_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='occupation',
            field=models.CharField(blank=True, choices=[('advocacy org staff', 'advocacy org staff'), ('attorneys/law students (not prosecutor)', 'attorneys/law students'), ('batterer intervention program staff', 'batterer intervention program staff'), ('corrections personnel', 'corrections personnel'), ('court personnel', 'court personnel'), ('disability org staff', 'disability org staff'), ('educators', 'educators'), ('elder org staff', 'elder org staff'), ('faith-based org staff', 'faith-based org staff'), ('government agency staff', 'gov agency staff'), ('health professionals', 'health professionals'), ('immigrant org staff', 'immigrant org staff'), ('law enforcement officers', 'law enforcement officers'), ('legal services staff (not attorney)', 'legal services staff'), ('mental health professionals', 'mpyental health professionals'), ('prosecutors', 'prosecutors'), ('sex offender treatment providers', 'sex offender treatment providers'), ('sexual assault nurse/forensic examiners', 'sexual assault nurse/forensic examiners'), ('social service org staff (non government)', 'social service org staff'), ('substance abuse org staff', 'substance abuse org staff'), ('supervised visitation and exchange center staff', 'supervised vistation and exchange center'), ('translators/interpreters', 'translators/interpreters'), ('tribal government/tribal government agency staff', 'tribal government/tribal government agency staff'), ('victim advocates (non-government)', 'victim advocates'), ('victim assistants (government)', 'victim assistants'), ('volunteers', 'volunteers'), ('other', 'other')], max_length=50, verbose_name='Occupation of Trainees'),
        ),
    ]
