# Generated by Django 3.0.8 on 2020-08-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main-page', '0012_auto_20200809_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='total_sess',
        ),
        migrations.RemoveField(
            model_name='ov',
            name='total_sess',
        ),
        migrations.RemoveField(
            model_name='safe_clinic',
            name='total_sess',
        ),
        migrations.AddField(
            model_name='map',
            name='total_accompaniments',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Accompaniments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ov',
            name='total_OV',
            field=models.PositiveIntegerField(default=0, verbose_name='Total OVs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safe_clinic',
            name='total_exams',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Rape Exams'),
            preserve_default=False,
        ),
    ]
