# Generated by Django 3.0.8 on 2020-08-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main-page', '0013_auto_20200809_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocacy',
            name='advocacy_immig_assist',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Immigration Assistance'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='advocacy_individ',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Individual Advocacy'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='advocacy_intervention',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Intervention with Employer, Creditor, etc.'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='advocacy_law_enforce',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Law Enforcement Interview Advocacy/Accompaniment'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='advocacy_med_forens',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Victim Advocacy/Accompaniment to Medical Forensic Exam'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='age_0_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 0-12'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='age_13_17',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 13-17'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='age_18_24',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 18-24'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='age_25_59',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 25-59'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='age_60_plus',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 60 and older'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='gender_agender',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Agender'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='gender_man',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Man'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='gender_nonbin',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Non-binary'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='gender_not_rep',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='gender_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Other'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='gender_other_text',
            field=models.TextField(default='', verbose_name='Gender Identity - Other Text'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='gender_woman',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Woman'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='race_amerind',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - American Indian/Alaska Native'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='race_asian',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Asian'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='race_black',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Black/African American'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='race_latinx',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Hispanic or Latino, Latina, and Latinx'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='race_multiple',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Multiple Races'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='race_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Some Other Race'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='race_pacific',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Native Hawaiian and Other Pacific Islander'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='race_unreported',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='race_untracked',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Tracked'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='race_white',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - White Non-Latino/Caucasian'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='sex_female',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Female'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='sex_inter',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Intersex'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='sex_male',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Male'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_bdsm',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - BDSM Practitioners'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_deaf',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Deaf/Hard of Hearing'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_disability',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Victims with Disabilities - Cognitive/Physical/Mental'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_homeless',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Homeless'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_immigrant',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Immigrants/Refugees/Asylum Seekers'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_lgbtq',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - LGBTQ'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_limited_eng',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Victims with Limited English Proficiency'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_non_monog',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Non-Monogamists'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Other'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_other_text',
            field=models.TextField(default='', verbose_name='Special Classification - Other Text'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_sex_work',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Sex Work Professionals'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='special_vet',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Veterans'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='total_ind',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Individuals'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='total_sess',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Sessions'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='victim_adult_sa',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Adult Sexual Assault'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='victim_as_child',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Adults Sexually Abused/Assaulted as Children'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='victim_child_porn',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Child Pornography'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='victim_child_sa',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Child Sexual Abuse/Assault'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='victim_human_traff',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Human Sex Trafficking'),
        ),
        migrations.AlterField(
            model_name='advocacy',
            name='victim_nonoff_caregiver',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Non-offending Caregivers'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='advocacy_immig_assist',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Immigration Assistance'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='advocacy_individ',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Individual Advocacy'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='advocacy_intervention',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Intervention with Employer, Creditor, etc.'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='advocacy_law_enforce',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Law Enforcement Interview Advocacy/Accompaniment'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='advocacy_med_forens',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Victim Advocacy/Accompaniment to Medical Forensic Exam'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='age_0_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 0-12'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='age_13_17',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 13-17'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='age_18_24',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 18-24'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='age_25_59',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 25-59'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='age_60_plus',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 60 and older'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='gender_agender',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Agender'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='gender_man',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Man'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='gender_nonbin',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Non-binary'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='gender_not_rep',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='gender_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Other'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='gender_other_text',
            field=models.TextField(default='', verbose_name='Gender Identity - Other Text'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='gender_woman',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Woman'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='race_amerind',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - American Indian/Alaska Native'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='race_asian',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Asian'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='race_black',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Black/African American'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='race_latinx',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Hispanic or Latino, Latina, and Latinx'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='race_multiple',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Multiple Races'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='race_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Some Other Race'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='race_pacific',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Native Hawaiian and Other Pacific Islander'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='race_unreported',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='race_untracked',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Tracked'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='race_white',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - White Non-Latino/Caucasian'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='sex_female',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Female'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='sex_inter',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Intersex'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='sex_male',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Male'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_bdsm',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - BDSM Practitioners'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_deaf',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Deaf/Hard of Hearing'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_disability',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Victims with Disabilities - Cognitive/Physical/Mental'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_homeless',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Homeless'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_immigrant',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Immigrants/Refugees/Asylum Seekers'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_lgbtq',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - LGBTQ'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_limited_eng',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Victims with Limited English Proficiency'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_non_monog',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Non-Monogamists'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Other'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_other_text',
            field=models.TextField(default='', verbose_name='Special Classification - Other Text'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_sex_work',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Sex Work Professionals'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='special_vet',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Veterans'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='total_ind',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Individuals'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='total_sess',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Sessions'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='victim_adult_sa',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Adult Sexual Assault'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='victim_as_child',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Adults Sexually Abused/Assaulted as Children'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='victim_child_porn',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Child Pornography'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='victim_child_sa',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Child Sexual Abuse/Assault'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='victim_human_traff',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Human Sex Trafficking'),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='victim_nonoff_caregiver',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Non-offending Caregivers'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='avg_length',
            field=models.FloatField(default=0, verbose_name='Average Length (Minutes)'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='avg_wait',
            field=models.FloatField(default=0, verbose_name='Average Wait Time (Minutes)'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='client_current',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Clients'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='client_new',
            field=models.PositiveIntegerField(default=0, verbose_name='New Clients'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='covid_mentioned',
            field=models.PositiveIntegerField(default=0, verbose_name='COVID-19 Mentioned'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='demo_veterans',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Veterans'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='demographic_minors',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Minors'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='gender_agender',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Agender'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='gender_man',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Man'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='gender_nonbin',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Non-binary'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='gender_not_rep',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='gender_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Other'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='gender_other_text',
            field=models.TextField(default='', verbose_name='Gender Identity - Other Text'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='gender_woman',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Woman'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='heard_TV',
            field=models.PositiveIntegerField(default=0, verbose_name='Heard Through TV'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='heard_friend_fam',
            field=models.PositiveIntegerField(default=0, verbose_name='Heard Through Friend or Family'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='heard_medical',
            field=models.PositiveIntegerField(default=0, verbose_name='Heard Through Medical Professional'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='heard_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Heard Through Other Source'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='heard_other_text',
            field=models.TextField(default='', verbose_name='Heard Through Other Source - Text'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='heard_radio',
            field=models.PositiveIntegerField(default=0, verbose_name='Heard Through Radio'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='heard_social',
            field=models.PositiveIntegerField(default=0, verbose_name='Heard Through Social Media'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='heard_website',
            field=models.PositiveIntegerField(default=0, verbose_name='Heard Through Website'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='highest_calls',
            field=models.PositiveIntegerField(default=0, verbose_name='Highest # Calls in 1 Day'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_contraceptives',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Access to Contraceptives'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_firearm_safety',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Firearm Safety'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_healthy_relationship',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Healthy Relationships'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_legal_def',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Legal Definitions'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_mandatory_report',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Mandatory Reporting Process'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_mental_health',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - General Mental Health'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_nop',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - NoP Support'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_police_codes',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Police Codes/Reporting Process'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_rape_crisis_info',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral -  General Rape Crisis Center Info'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_sac_info',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - General SAC Info'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_sex_ed',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Sex Education'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_stalking',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Stalking/Harassment'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_survivor',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Survivor Support'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_teen_dating_violence',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Teen Dating Violence'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_trauma_response',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Trauma Response/Impact'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='info_workplace_harass',
            field=models.PositiveIntegerField(default=0, verbose_name='Information Referral - Workplace Harassment'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='lang_english',
            field=models.PositiveIntegerField(default=0, verbose_name='Preferred Language - English'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='lang_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Preferred Language - Other'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='lang_other_text',
            field=models.TextField(default='', verbose_name='Preferred Language - Other Text'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='lang_spanish',
            field=models.PositiveIntegerField(default=0, verbose_name='Preferred Language - Spanish'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='race_amerind',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - American Indian/Alaska Native'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='race_asian',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Asian'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='race_black',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Black/African American'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='race_latinx',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Hispanic or Latino, Latina, and Latinx'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='race_multiple',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Multiple Races'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='race_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Some Other Race'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='race_pacific',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Native Hawaiian and Other Pacific Islander'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='race_unreported',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='race_untracked',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Tracked'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='race_white',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - White Non-Latino/Caucasian'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='reason_concern_child',
            field=models.PositiveIntegerField(default=0, verbose_name='Reason - Concerned for a Child'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='reason_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Reason - Other'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='reason_other_text',
            field=models.TextField(default='', verbose_name='Reason - Other Text'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='reason_self_crisis',
            field=models.PositiveIntegerField(default=0, verbose_name='Reason - Self in Crisis'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='reason_support_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Reason - Support for Someone Else'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='reason_triggered',
            field=models.PositiveIntegerField(default=0, verbose_name='Reason - Triggered'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_addiction',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Addiction Services'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_advocacy',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Advocacy Services'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_bilingual',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Bilingual Services'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_disability',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Disability Resources'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_financial',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Financial Resources'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_food',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Food Access'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_hospital',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Hospital Services'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_housing',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Housing Resources'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_legal',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Legal Services'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_mental_health',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Mental Health/Therapy'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Other'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_shelter',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Shelter Services'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_social',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Social Services'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_support_group',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Support Group'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_survivor',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Survivor Resources'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='resource_veteran',
            field=models.PositiveIntegerField(default=0, verbose_name='Resource Referral - Veterans Resources'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='total_calls',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Calls'),
        ),
        migrations.AlterField(
            model_name='development',
            name='new_donors',
            field=models.PositiveIntegerField(default=0, verbose_name='New Donors'),
        ),
        migrations.AlterField(
            model_name='development',
            name='new_foundations',
            field=models.PositiveIntegerField(default=0, verbose_name='New Foundations/Grants'),
        ),
        migrations.AlterField(
            model_name='development',
            name='over_1000',
            field=models.PositiveIntegerField(default=0, verbose_name='Gifts over $1000'),
        ),
        migrations.AlterField(
            model_name='development',
            name='percent_goal_met',
            field=models.PositiveIntegerField(default=0, verbose_name='Percentage of Monthly Goal Met'),
        ),
        migrations.AlterField(
            model_name='development',
            name='recurring_donors',
            field=models.PositiveIntegerField(default=0, verbose_name='Recurring Donors'),
        ),
        migrations.AlterField(
            model_name='development',
            name='recurring_gift_avg',
            field=models.PositiveIntegerField(default=0, verbose_name='Recurring Gift Average'),
        ),
        migrations.AlterField(
            model_name='development',
            name='total_raised',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Amount Raised'),
        ),
        migrations.AlterField(
            model_name='map',
            name='advocacy_immig_assist',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Immigration Assistance'),
        ),
        migrations.AlterField(
            model_name='map',
            name='advocacy_individ',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Individual Advocacy'),
        ),
        migrations.AlterField(
            model_name='map',
            name='advocacy_intervention',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Intervention with Employer, Creditor, etc.'),
        ),
        migrations.AlterField(
            model_name='map',
            name='advocacy_law_enforce',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Law Enforcement Interview Advocacy/Accompaniment'),
        ),
        migrations.AlterField(
            model_name='map',
            name='advocacy_med_forens',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Victim Advocacy/Accompaniment to Medical Forensic Exam'),
        ),
        migrations.AlterField(
            model_name='map',
            name='age_0_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 0-12'),
        ),
        migrations.AlterField(
            model_name='map',
            name='age_13_17',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 13-17'),
        ),
        migrations.AlterField(
            model_name='map',
            name='age_18_24',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 18-24'),
        ),
        migrations.AlterField(
            model_name='map',
            name='age_25_59',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 25-59'),
        ),
        migrations.AlterField(
            model_name='map',
            name='age_60_plus',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 60 and older'),
        ),
        migrations.AlterField(
            model_name='map',
            name='gender_agender',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Agender'),
        ),
        migrations.AlterField(
            model_name='map',
            name='gender_man',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Man'),
        ),
        migrations.AlterField(
            model_name='map',
            name='gender_nonbin',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Non-binary'),
        ),
        migrations.AlterField(
            model_name='map',
            name='gender_not_rep',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='map',
            name='gender_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Other'),
        ),
        migrations.AlterField(
            model_name='map',
            name='gender_other_text',
            field=models.TextField(default='', verbose_name='Gender Identity - Other Text'),
        ),
        migrations.AlterField(
            model_name='map',
            name='gender_woman',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Woman'),
        ),
        migrations.AlterField(
            model_name='map',
            name='race_amerind',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - American Indian/Alaska Native'),
        ),
        migrations.AlterField(
            model_name='map',
            name='race_asian',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Asian'),
        ),
        migrations.AlterField(
            model_name='map',
            name='race_black',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Black/African American'),
        ),
        migrations.AlterField(
            model_name='map',
            name='race_latinx',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Hispanic or Latino, Latina, and Latinx'),
        ),
        migrations.AlterField(
            model_name='map',
            name='race_multiple',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Multiple Races'),
        ),
        migrations.AlterField(
            model_name='map',
            name='race_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Some Other Race'),
        ),
        migrations.AlterField(
            model_name='map',
            name='race_pacific',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Native Hawaiian and Other Pacific Islander'),
        ),
        migrations.AlterField(
            model_name='map',
            name='race_unreported',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='map',
            name='race_untracked',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Tracked'),
        ),
        migrations.AlterField(
            model_name='map',
            name='race_white',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - White Non-Latino/Caucasian'),
        ),
        migrations.AlterField(
            model_name='map',
            name='sex_female',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Female'),
        ),
        migrations.AlterField(
            model_name='map',
            name='sex_inter',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Intersex'),
        ),
        migrations.AlterField(
            model_name='map',
            name='sex_male',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Male'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_bdsm',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - BDSM Practitioners'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_deaf',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Deaf/Hard of Hearing'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_disability',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Victims with Disabilities - Cognitive/Physical/Mental'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_homeless',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Homeless'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_immigrant',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Immigrants/Refugees/Asylum Seekers'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_lgbtq',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - LGBTQ'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_limited_eng',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Victims with Limited English Proficiency'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_non_monog',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Non-Monogamists'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Other'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_other_text',
            field=models.TextField(default='', verbose_name='Special Classification - Other Text'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_sex_work',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Sex Work Professionals'),
        ),
        migrations.AlterField(
            model_name='map',
            name='special_vet',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Veterans'),
        ),
        migrations.AlterField(
            model_name='map',
            name='total_accompaniments',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Accompaniments'),
        ),
        migrations.AlterField(
            model_name='map',
            name='total_ind',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Individuals'),
        ),
        migrations.AlterField(
            model_name='map',
            name='victim_adult_sa',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Adult Sexual Assault'),
        ),
        migrations.AlterField(
            model_name='map',
            name='victim_as_child',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Adults Sexually Abused/Assaulted as Children'),
        ),
        migrations.AlterField(
            model_name='map',
            name='victim_child_porn',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Child Pornography'),
        ),
        migrations.AlterField(
            model_name='map',
            name='victim_child_sa',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Child Sexual Abuse/Assault'),
        ),
        migrations.AlterField(
            model_name='map',
            name='victim_human_traff',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Human Sex Trafficking'),
        ),
        migrations.AlterField(
            model_name='map',
            name='victim_nonoff_caregiver',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Non-offending Caregivers'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='advocacy_immig_assist',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Immigration Assistance'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='advocacy_individ',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Individual Advocacy'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='advocacy_intervention',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Intervention with Employer, Creditor, etc.'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='advocacy_law_enforce',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Law Enforcement Interview Advocacy/Accompaniment'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='advocacy_med_forens',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Victim Advocacy/Accompaniment to Medical Forensic Exam'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='age_0_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 0-12'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='age_13_17',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 13-17'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='age_18_24',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 18-24'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='age_25_59',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 25-59'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='age_60_plus',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 60 and older'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='gender_agender',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Agender'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='gender_man',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Man'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='gender_nonbin',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Non-binary'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='gender_not_rep',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='gender_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Other'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='gender_other_text',
            field=models.TextField(default='', verbose_name='Gender Identity - Other Text'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='gender_woman',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Woman'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='race_amerind',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - American Indian/Alaska Native'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='race_asian',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Asian'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='race_black',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Black/African American'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='race_latinx',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Hispanic or Latino, Latina, and Latinx'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='race_multiple',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Multiple Races'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='race_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Some Other Race'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='race_pacific',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Native Hawaiian and Other Pacific Islander'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='race_unreported',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='race_untracked',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Tracked'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='race_white',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - White Non-Latino/Caucasian'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='sex_female',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Female'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='sex_inter',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Intersex'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='sex_male',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Male'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_bdsm',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - BDSM Practitioners'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_deaf',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Deaf/Hard of Hearing'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_disability',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Victims with Disabilities - Cognitive/Physical/Mental'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_homeless',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Homeless'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_immigrant',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Immigrants/Refugees/Asylum Seekers'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_lgbtq',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - LGBTQ'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_limited_eng',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Victims with Limited English Proficiency'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_non_monog',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Non-Monogamists'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Other'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_other_text',
            field=models.TextField(default='', verbose_name='Special Classification - Other Text'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_sex_work',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Sex Work Professionals'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='special_vet',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Veterans'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='total_OV',
            field=models.PositiveIntegerField(default=0, verbose_name='Total OVs'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='total_ind',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Individuals'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='victim_adult_sa',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Adult Sexual Assault'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='victim_as_child',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Adults Sexually Abused/Assaulted as Children'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='victim_child_porn',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Child Pornography'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='victim_child_sa',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Child Sexual Abuse/Assault'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='victim_human_traff',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Human Sex Trafficking'),
        ),
        migrations.AlterField(
            model_name='ov',
            name='victim_nonoff_caregiver',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Non-offending Caregivers'),
        ),
        migrations.AlterField(
            model_name='prevention',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Training Duration'),
        ),
        migrations.AlterField(
            model_name='prevention',
            name='num_attendees',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Attendees'),
        ),
        migrations.AlterField(
            model_name='prevention',
            name='topic_other',
            field=models.TextField(default='', verbose_name='Other Topic'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='advocacy_immig_assist',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Immigration Assistance'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='advocacy_individ',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Individual Advocacy'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='advocacy_intervention',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Intervention with Employer, Creditor, etc.'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='advocacy_law_enforce',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Law Enforcement Interview Advocacy/Accompaniment'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='advocacy_med_forens',
            field=models.PositiveIntegerField(default=0, verbose_name='Personal Advocacy/Achievement - Victim Advocacy/Accompaniment to Medical Forensic Exam'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='age_0_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 0-12'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='age_13_17',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 13-17'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='age_18_24',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 18-24'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='age_25_59',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 25-59'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='age_60_plus',
            field=models.PositiveIntegerField(default=0, verbose_name='Age - 60 and older'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='gender_agender',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Agender'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='gender_man',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Man'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='gender_nonbin',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Non-binary'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='gender_not_rep',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='gender_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Other'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='gender_other_text',
            field=models.TextField(default='', verbose_name='Gender Identity - Other Text'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='gender_woman',
            field=models.PositiveIntegerField(default=0, verbose_name='Gender Identity - Woman'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='race_amerind',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - American Indian/Alaska Native'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='race_asian',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Asian'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='race_black',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Black/African American'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='race_latinx',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Hispanic or Latino, Latina, and Latinx'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='race_multiple',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Multiple Races'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='race_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Some Other Race'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='race_pacific',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Native Hawaiian and Other Pacific Islander'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='race_unreported',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Reported'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='race_untracked',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - Not Tracked'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='race_white',
            field=models.PositiveIntegerField(default=0, verbose_name='Race/Ethnicity - White Non-Latino/Caucasian'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='sex_female',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Female'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='sex_inter',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Intersex'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='sex_male',
            field=models.PositiveIntegerField(default=0, verbose_name='Sex - Male'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_bdsm',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - BDSM Practitioners'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_deaf',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Deaf/Hard of Hearing'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_disability',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Victims with Disabilities - Cognitive/Physical/Mental'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_homeless',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Homeless'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_immigrant',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Immigrants/Refugees/Asylum Seekers'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_lgbtq',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - LGBTQ'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_limited_eng',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Victims with Limited English Proficiency'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_non_monog',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Non-Monogamists'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Other'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_other_text',
            field=models.TextField(default='', verbose_name='Special Classification - Other Text'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_sex_work',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Sex Work Professionals'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='special_vet',
            field=models.PositiveIntegerField(default=0, verbose_name='Special Classification - Veterans'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='total_exams',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Rape Exams'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='total_ind',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Individuals'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='victim_adult_sa',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Adult Sexual Assault'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='victim_as_child',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Adults Sexually Abused/Assaulted as Children'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='victim_child_porn',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Child Pornography'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='victim_child_sa',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Child Sexual Abuse/Assault'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='victim_human_traff',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Human Sex Trafficking'),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='victim_nonoff_caregiver',
            field=models.PositiveIntegerField(default=0, verbose_name='Victimization Types - Non-offending Caregivers'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Training Duration (min)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='num_attendees',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Attendees'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_type_other',
            field=models.TextField(default='', verbose_name='Type of Training - Other Text'),
        ),
    ]
