# Generated by Django 3.0.8 on 2020-07-26 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_auto_20200725_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocacy',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='clinical',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='map',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ov',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='safe_clinic',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
