# Generated by Django 3.0.8 on 2020-07-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_crisis_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisis_line',
            options={'verbose_name': 'Crisis Line Team Entry', 'verbose_name_plural': 'Crisis Line Team Entries'},
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='avg_length',
            field=models.FloatField(verbose_name='Average Length (Minutes)'),
        ),
        migrations.AlterField(
            model_name='crisis_line',
            name='avg_wait',
            field=models.FloatField(verbose_name='Average Wait Time (Minutes)'),
        ),
    ]
