# Generated by Django 3.1.3 on 2020-11-30 22:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0009_auto_20201025_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_topic',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('advocate response', 'advocate response'), ('child witnesses', 'child witnesses'), ('confidentiality', 'confidentiality'), ('dating violence overview, dynamics, and services', 'dating violence overview, dynamics, and services'), ('mandatory reporting requirements', 'mandatory reporting requirements'), ('response to victims/survivors who have been trafficked', 'response to victims/survivors who have been trafficked'), ('safety planning for victims/survivors', 'safety planning for victims/survivors'), ('sexual assault overview, dynamics, and services', 'sexual assault overview, dynamics, and services'), ('stalking overview, dynamics, and services', 'stalking overview, dynamics, and services'), ('supervised visitation and exchange', 'supervised visitation and exchange'), ('civil court procedures', 'civil court procedures'), ('criminal court procedures', 'criminal court procedures'), ('domestic violence committed by law enforcement personnel', 'domestic violence committed by law enforcement personnel'), ('domestic violence statutes/codes', 'domestic violence statutes/codes'), ('firearms and domestic violence', 'firearms and domestic violence'), ('homicide prevention', 'homicide prevention'), ('identification and arrest of predominant aggressor', 'identification and arrest of predominant aggressor'), ('immigration', 'immigration'), ('judicial response', 'judicial response'), ('law enforcement response', 'law enforcement response'), ('pro-arrest policies', 'pro-arrest policies'), ('probation response', 'probation response'), ('prosecution response', 'prosecution response'), ('protection orders', 'protection orders'), ('sexual assault evidence collection kits', 'sexual assault evidence collection kits'), ('sexual assault statues/codes', 'sexual assault statues/codes'), ('sexual assault forensic examination', 'sexual assault forensic examination'), ('stalking statues/codes', 'stalking statues/codes'), ('tribal jurisdiction and public law 280', 'tribal jurisdiction and public law 280'), ('are American Indian or Alaska Native', 'are American Indian or Alaska Native'), ('are Asian', 'are Asian'), ('are Black or African American', 'are Black or African American'), ('are Deaf or hard of hearing', 'are Deaf or hard of hearing'), ('are elderly', 'are elderly'), ('are Hispanice or Latino', 'are Hispanice or Latino'), ('are homeless or living in poverty', 'are homeless or living in poverty'), ('are immigrants, refugees, or asylum seekers', 'are immigrants, refugees, or asylum seekers'), ('are in correctional settings', 'are in correctional settings'), ('are lesbian, gay, bisexual, transgender, or intersex', 'are lesbian, gay, bisexual, transgender, or intersex'), ('are Native Hawaiian or other Pacific Islander', 'are Native Hawaiian or other Pacific Islander'), ('have disabilities', 'have disabilities'), ('have limited English proficiency', 'have limited English proficiency'), ('have mental health issues', 'have mental health issues'), ('have substance abuse issues', 'have substance abuse issues'), ('live in rural areas', 'live in rural areas'), ('Community response to sexual assault', 'Community response to sexual assault'), ('Coordinated community response', 'Coordinated community response'), ('Response teams (DART, DVRT, SART)', 'Response teams (DART, DVRT, SART)'), ('Technology', 'Technology')], default='', max_length=1475),
            preserve_default=False,
        ),
    ]
