# Generated by Django 3.1.3 on 2021-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0014_auto_20201221_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocacy',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='clinical',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='clinical_voca',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='map',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='ov',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='safe_clinic',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Year'),
        ),
    ]
