# Generated by Django 3.1.3 on 2021-01-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0015_auto_20210101_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis_line',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='development',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='prevention',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='training',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Year'),
        ),
    ]
