# Generated by Django 3.1.3 on 2021-01-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0016_auto_20210101_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocacy',
            name='emp_name',
            field=models.TextField(default='Enter your name here', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='clinical',
            name='emp_name',
            field=models.TextField(default='Enter your name here', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='clinical_voca',
            name='emp_name',
            field=models.TextField(default='Enter your name here', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='map',
            name='emp_name',
            field=models.TextField(default='Enter your name here', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='ov',
            name='emp_name',
            field=models.TextField(default='Enter your name here', verbose_name='Employee Name'),
        ),
        migrations.AddField(
            model_name='safe_clinic',
            name='emp_name',
            field=models.TextField(default='Enter your name here', verbose_name='Employee Name'),
        ),
    ]
